apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: jenkins
  name: jenkins-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: jenkins
  template: 
    metadata: 
      labels: 
        app: jenkins
     spec:
       containers:
         - image: jenkins/jenkins:lts
           name: jenkins
           volumeMounts:
             - mountPath: "/var/jenkins_home"
               name: jenkins-volume
           securityContext:
             runAsUser: 0
       nodeSelector:
         environment: qa
       volumes:
         - name: jenkins-volume
           persistentVolumeClaim:
             claimName: jenkins-home-claim 
